# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emaantracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emaantracker

  target 'emaantracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emaantrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'emaantracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emaantracker-tvOS

  target 'emaantracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# react-native-google-place-picker dependencies

pod 'GooglePlacePicker', '= 2.0.1'
pod 'GooglePlaces', '= 2.0.1'
pod 'GoogleMaps', '= 2.0.1'
